version: '3.1'

services:
  back-node: 
    build: 
      context: ./back
    ports:
      - "3001:5000"
    container_name: freezer-back
    # environment:
    depends_on:
      - postgres
    networks:
      - backend
      # - frontend

  # front-node: 
  #   build: 
  #     context: ./front
  #     args:
  #     - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
  #   ports:
  #   container_name: freezer-front
  #   environment:
  #   depends_on:
  #     - back-node
  #   networks:
  #     - frontend

  postgres: 
    image: postgres
    restart: always
    # ports:
    #   - "5442:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-freezer}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pg_data:

networks:
  backend:
  # - frontend

