version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5442:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-12345678}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
    - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgresql

volumes:
  pg_data:
