export const DELETE_ONE = 'DELETE_ONE'
export const SHOW_BODY = 'SHOW_BODY'
export const CHECK = 'CHECK'

export const COPY = 'COPY'
export const DELETE_ALL = 'DELETE-ALL'
export const INSERT = 'INSERT'

export const ADD = 'ADD'
export const UPDATE_ADD_INPUT_NUMBER = 'UPDATE_ADD_INPUT_NUMBER'
export const UPDATE_ADD_INPUT_UNIT = 'UPDATE_ADD_INPUT_UNIT'
export const UPDATE_ADD_INPUT_TEXT = 'UPDATE_ADD_INPUT_TEXT'

export const UPDATE_EDIT_INPUT_TEXT = 'UPDATE_EDIT_INPUT_TEXT'
export const UPDATE_EDIT_INPUT_NUMBER = 'UPDATE_EDIT_INPUT_NUMBER'
export const UPDATE_EDIT_INPUT_UNIT = 'UPDATE_EDIT_INPUT_UNIT'








